### ISSUE TITLE
Pflichtfeldprüfung auf einem TInvoice-Objekt vor XML-Validierung

### ISSUE THREAD

**Issue by NMeyer2307** [LandrixSoftware/ZUGFeRD-for-Delphi#30]
Hallo zusammen,

gibt es die Möglichkeit, bevor man die Gültigkeit einer XRechnung mit der Methode XRechnungValidationHelperJava.Validate(xml...) prüft, eine Validierung auf einem TInvoice-Objekt durchzuführen? Insbesondere wäre es hilfreich, zumindest zu überprüfen, ob alle Pflichtfelder gesetzt sind, bevor das XML generiert und validiert wird.

Vielen Dank im Voraus für jede Rückmeldung!

**Comment by landrix** [comment]
Es gibt

https://github.com/LandrixSoftware/XRechnung-for-Delphi/blob/7803c665cc636cf01f608407e5e908e435704bec/intf.XRechnung.pas#L123

Das könnte noch etwas erweitert werden.

**Comment by NMeyer2307** [comment]
Danke für die Antwort.

Gibt es irgendwo eine Übersicht oder Dokumentation, die zeigt, welche Attribute im **TInvoice**-Objekt Pflicht sind? 

Vielen Dank im Voraus.

**Comment by landrix** [comment]
In der Beispielanwendung gibt es ein Minimalbeispiel.
