### ISSUE TITLE
ZUGFeRD Validierung mit Original und Test schlägt fehl

### ISSUE THREAD

**Issue by CaptainDelphi** [LandrixSoftware/ZUGFeRD-for-Delphi#33]
Hallo,
bei der ZUGFeRD-Validierung mit Original-XML und Test-XML kommt es zu einer Differenz.

Im geladenen Test fehlt:
<ram:PayeePartyCreditorFinancialAccount>
          <ram:IBANID>DE832855000000012345678</ram:IBANID>
          <ram:AccountName>Firma GmbH</ram:AccountName>
        </ram:PayeePartyCreditorFinancialAccount>
MfG
Frank

**Comment by landrix** [comment]
behoben unter https://github.com/LandrixSoftware/XRechnung-for-Delphi

**Comment by CaptainDelphi** [comment]
Vielen Dank für die schnelle Änderung.
MfG Frank
