### ISSUE TITLE
Kompilierfehler in intf.ZUGFeRDInvoiceDescriptor23CIIReader

### ISSUE THREAD

**Issue by CaptainDelphi** [LandrixSoftware/ZUGFeRD-for-Delphi#34]
In Zeile 401 muss CalculatedAmount übergeben werden.

nodes := doc.SelectNodes('//ram:ApplicableHeaderTradeSettlement/ram:ApplicableTradeTax');
  for i := 0 to nodes.length-1 do
  begin
    Result.AddApplicableTradeTax(TZUGFeRDXmlUtils.NodeAsDecimal(nodes[i], './/ram:CalculatedAmount', 0),

MfG Frank

**Comment by landrix** [comment]
wird es das nicht?

https://github.com/LandrixSoftware/ZUGFeRD-for-Delphi/blob/87c1e31914f4289398a46cfcc3a7203871f91257/intf.ZUGFeRDInvoiceDescriptor23CIIReader.pas#L401
